[template]
src = "nginx-config.conf.tmpl"
dest = "/etc/nginx/server.conf"
keys = [
  "BW_CA_PATH",
  "BW_CAPTCHA",
  "BW_CSP",
  "BW_DIFFIEHELLMAN_PATH",
  "BW_DOMAIN",
  "BW_ENABLE_KEY_CONNECTOR",
  "BW_ENABLE_SSL",
  "BW_REAL_IPS",
  "BW_SERVICE_NAME_ADMIN",
  "BW_SERVICE_NAME_API",
  "BW_SERVICE_NAME_ATTACHMENTS",
  "BW_SERVICE_NAME_EVENTS",
  "BW_SERVICE_NAME_ICONS",
  "BW_SERVICE_NAME_IDENTITY",
  "BW_SERVICE_NAME_KEY_CONNECTOR",
  "BW_SERVICE_NAME_NOTIFICATIONS",
  "BW_SERVICE_NAME_SSO",
  "BW_SERVICE_NAME_WEB",
  "BW_SERVICE_PORT_ADMIN",
  "BW_SERVICE_PORT_API",
  "BW_SERVICE_PORT_ATTACHMENTS",
  "BW_SERVICE_PORT_EVENTS",
  "BW_SERVICE_PORT_ICONS",
  "BW_SERVICE_PORT_IDENTITY",
  "BW_SERVICE_PORT_KEY_CONNECTOR",
  "BW_SERVICE_PORT_SSO",
  "BW_SERVICE_PORT_WEB",
  "BW_SSL_CERT",
  "BW_SSL_CIPHERS",
  "BW_SSL_KEY",
  "BW_SSL_PROTOCOLS"
]