version: '3'

services:
  bitwarden_server:
    image: mcr.microsoft.com/devcontainers/dotnet:0-6.0
    volumes:
      - ../../:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  bitwarden_mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: 'd3vP@ssw0rd!' # update this in your secrets.json file if you change this!!!
      MSSQL_PID: Developer
    volumes:
      - edgesql_dev_data:/var/opt/mssql
      - ../../util/Migrator:/mnt/migrator/
      - ../../dev/helpers/mssql:/mnt/helpers
      - ../../dev/.data/mssql:/mnt/data
    network_mode: service:bitwarden_server

  bitwarden_mail:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    network_mode: service:bitwarden_server
    
volumes:
  edgesql_dev_data:
