[package]
name = "bitwarden-akd-configuration"
edition.workspace = true
version.workspace = true
authors.workspace = true
license-file.workspace = true
keywords.workspace = true

[dependencies]
akd.workspace = true
blake3.workspace = true
config = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
uuid = { version = "1.18.1", features = ["serde"] }

[lints]
workspace = true

[features]
config = ["dep:config", "dep:serde"]
default = ["config"]
