---
name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  enforce-label:
    name: EnforceLabel
    runs-on: ubuntu-20.04
    steps:
      - name: Enforce Label
        uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024
        with:
          BANNED_LABELS: "hold,DB-migrations-changed,needs-qa"
